SELECT * FROM VIEW_SUICIDIO WHERE YEAR = 1997 ORDER BY SEX, AGE;

SELECT
	SUICIDIO.YEAR,
	SUICIDIO.SEX,
	SUICIDIO.AGE,
	SUICIDIO.SUICIDES_NO
FROM VIEW_SUICIDIO SUICIDIO
	WHERE SUICIDIO.SEX = 'male' ORDER BY SUICIDIO.YEAR, SUICIDIO.  AGE, SUICIDIO.SUICIDES_NO;
	
SELECT
	SUICIDIO.YEAR,
	SUICIDIO.SEX,
	SUICIDIO.AGE,
	SUICIDIO.SUICIDES_NO
FROM VIEW_SUICIDIO SUICIDIO
	WHERE SUICIDIO.SEX = 'male' AND SUICIDIO.AGE = '15-24 years'
	ORDER BY SUICIDIO.SUICIDES_NO DESC;