SELECT SEX, SUICIDES_NO, SUICIDES_NO^2 FROM VIEW_SUICIDIO WHERE AGE = '5-14 years' AND SEX = 'male';

-- CREATE OR REPLACE VIEW VIEW_SUICIDIO_MEDIDA_DISPERSAO AS
SELECT 	
	COUNT(SUICIDES_NO) NUM_REGISTRO,
	AGE FAIXA_ETARIA,
	SEX GENERO,
	SUM(SUICIDES_NO) TOTAL_SUICIDIO, 
	SUM(SUICIDES_NO^2) POTENCIA_TOTAL_SUICIDIO,
	trunc( AVG(SUICIDES_NO), 2 ) MEDIA_NUM_SUICIDIO,
	(
		sqrt(((SUM(SUICIDES_NO^2))-((SUM(SUICIDES_NO)^2)/COUNT(SUICIDES_NO)))/COUNT(SUICIDES_NO)-1)
	) DESVIO_PADRAO,
	(
		(sqrt(((SUM(SUICIDES_NO^2))-((SUM(SUICIDES_NO)^2)/COUNT(SUICIDES_NO)))/COUNT(SUICIDES_NO)-1)/trunc( AVG(SUICIDES_NO), 2 ))
	)*100 COEFICIENTE_VARIACAO_PERCIL,
	(
		(sqrt(((SUM(SUICIDES_NO^2))-((SUM(SUICIDES_NO)^2)/COUNT(SUICIDES_NO)))/COUNT(SUICIDES_NO)-1)/trunc( AVG(SUICIDES_NO), 2 ))
	) COEFICIENTE_VARIACAO
FROM VIEW_SUICIDIO GROUP BY AGE, SEX ORDER BY SEX;
